Repository ProvedCode/backend, pull requests merged in 2023-04, with the labels that each got.

#63 S2US1
  pom.xml
  src/main/java/com/provedcode/ProvedCodeApplication.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/mapper/TalentMapper.java
  src/main/java/com/provedcode/talent/mapper/TalentProofMapper.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentMapperImpl.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentProofMapperImpl.java
  src/main/java/com/provedcode/talent/model/ProofStatus.java
  src/main/java/com/provedcode/talent/model/dto/FullTalentDTO.java
  src/main/java/com/provedcode/talent/model/dto/ProofDTO.java
  src/main/java/com/provedcode/talent/model/dto/ShortTalentDTO.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/model/entity/TalentTalents.java
  src/main/java/com/provedcode/talent/model/response/ShortTalent.java
  src/main/java/com/provedcode/talent/repo/TalentProofRepository.java
  src/main/java/com/provedcode/talent/repo/TalentRepository.java
  src/main/java/com/provedcode/talent/repo/TalentSkillRepository.java
  src/main/java/com/provedcode/talent/repo/db/TalentEntityRepository.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/user/controller/AuthenticationController.java
  src/main/java/com/provedcode/user/mapper/UserInfoMapper.java
  src/main/java/com/provedcode/user/mapper/impl/UserInfoMapperImpl.java
  src/main/java/com/provedcode/user/model/Role.java
  src/main/java/com/provedcode/user/model/entity/Authority.java
  src/main/java/com/provedcode/user/model/entity/UserAuthority.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/repo/AuthorityRepository.java
  src/main/java/com/provedcode/user/repo/UserAuthorityRepository.java
  src/main/java/com/provedcode/user/service/impl/AuthenticationServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: :frog: backend, user story #1

#65 S2US3
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/model/dto/FullProofDTO.java
  src/main/java/com/provedcode/talent/repo/TalentProofRepository.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
Labels: user story #3

#66 S2 us2 5 8
  pom.xml
  src/main/java/com/provedcode/ProvedCodeApplication.java
  src/main/java/com/provedcode/config/PageProperties.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/model/dto/AddProofDTO.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/utill/ValidateTalentForCompliance.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: :frog: backend, user story #2, user story #5, user story #8

#69 For merge
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/model/dto/ProofDTO.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/utill/ValidateTalentForCompliance.java
Labels: :frog: backend, user story #5

#70 S2US6-7
  src/main/java/com/provedcode/config/InitConfig.java
  src/main/java/com/provedcode/config/PageProperties.java
  src/main/java/com/provedcode/config/PropsConfig.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/handlers/TalentExceptionHandler.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/mapper/TalentMapper.java
  src/main/java/com/provedcode/talent/mapper/TalentProofMapper.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentMapperImpl.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentProofMapperImpl.java
  src/main/java/com/provedcode/talent/model/dto/ProofDTO.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/repo/TalentProofRepository.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/utill/ValidateTalentForCompliance.java
  src/main/java/com/provedcode/user/model/entity/Authority.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/repo/UserInfoRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: user story #6, user story #7

#93 Task#1-2
  src/main/java/com/provedcode/kudos/KudosController.java
  src/main/java/com/provedcode/kudos/KudosRepository.java
  src/main/java/com/provedcode/kudos/KudosService.java
  src/main/java/com/provedcode/kudos/model/entity/Kudos.java
  src/main/java/com/provedcode/kudos/model/response/KudosAmount.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentAttachedFile.java
  src/main/java/com/provedcode/talent/model/entity/TalentContact.java
  src/main/java/com/provedcode/talent/model/entity/TalentDescription.java
  src/main/java/com/provedcode/talent/model/entity/TalentLink.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/model/entity/TalentTalents.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/utill/ValidateTalentForCompliance.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/service/impl/AuthenticationServiceImpl.java
  src/main/resources/schema.sql
Labels: :frog: backend, user story #1

#96 Task#3 As a talent I want to estimate proofs of other talents by givi…
  src/main/java/com/provedcode/kudos/KudosController.java
  src/main/java/com/provedcode/kudos/KudosRepository.java
  src/main/java/com/provedcode/kudos/KudosService.java
Labels: :frog: backend, user story #1

#97 S3.1 us1.task 4
  src/main/java/com/provedcode/kudos/KudosService.java
  src/main/java/com/provedcode/kudos/controller/KudosController.java
  src/main/java/com/provedcode/kudos/model/entity/Kudos.java
  src/main/java/com/provedcode/kudos/repository/KudosRepository.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
Labels: :frog: backend, user story #1

#99 S3.1US1
  src/main/java/com/provedcode/kudos/controller/KudosController.java
  src/main/java/com/provedcode/kudos/model/entity/Kudos.java
  src/main/java/com/provedcode/kudos/model/response/KudosAmount.java
  src/main/java/com/provedcode/kudos/repository/KudosRepository.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentAttachedFile.java
  src/main/java/com/provedcode/talent/model/entity/TalentContact.java
  src/main/java/com/provedcode/talent/model/entity/TalentDescription.java
  src/main/java/com/provedcode/talent/model/entity/TalentLink.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/model/entity/TalentTalents.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/utill/ValidateTalentForCompliance.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/service/impl/AuthenticationServiceImpl.java
  src/main/resources/schema.sql
Labels: :frog: backend, user story #1

#100 AWS
  src/main/java/com/provedcode/aws/controller/AWSS3BucketController.java
  src/main/java/com/provedcode/aws/controller/S3Controller.java
  src/main/java/com/provedcode/aws/service/FileService.java
  src/main/java/com/provedcode/aws/service/S3Service.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/resources/schema.sql
Labels: :frog: backend, general

#101 Liquibase merge
  pom.xml
  src/main/java/com/provedcode/config/InitConfig.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/changeset/add-data.sql
  src/main/resources/db/changelog/changeset/create-tables.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/main/resources/schema.sql
Labels: :frog: backend, general
