Repository ProvedCode/backend, pull requests merged in 2023-03, with the labels that each got.

#32 Tasks 3 6
  src/main/java/com/provedcode/ProvedCodeApplication.java
  src/main/java/com/provedcode/config/PageConfig.java
  src/main/java/com/provedcode/handlers/TalentExceptionHandler.java
  src/main/java/com/provedcode/talent/TalentController.java
  src/main/java/com/provedcode/talent/mapper/TalentMapper.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentMapperImpl.java
  src/main/java/com/provedcode/talent/model/dto/FullTalentDTO.java
  src/main/java/com/provedcode/talent/model/dto/ShortTalentDTO.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/repo/TalentRepository.java
  src/main/java/com/provedcode/talent/repo/db/TalentEntityRepository.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/service/mock/TalentServiceMock.java
  src/main/resources/pagination.properties
Labels: :frog: backend, user story #1

#35 user-story-1
  pom.xml
  src/main/java/com/provedcode/config/PageProperties.java
  src/main/java/com/provedcode/config/PropsConfig.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/talent/TalentController.java
  src/main/java/com/provedcode/talent/mapper/TalentMapper.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentMapperImpl.java
  src/main/java/com/provedcode/talent/repo/TalentRepository.java
  src/main/java/com/provedcode/talent/repo/db/TalentEntityRepository.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/talent/service/mock/TalentServiceMock.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/pagination.properties
  src/main/resources/schema.sql
Labels: :frog: backend

#60 UserStory2
  pom.xml
  src/main/java/com/provedcode/config/InitConfig.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/handlers/TalentExceptionHandler.java
  src/main/java/com/provedcode/talent/TalentController.java
  src/main/java/com/provedcode/talent/mapper/impl/TalentMapperImpl.java
  src/main/java/com/provedcode/talent/model/dto/FullTalentDTO.java
  src/main/java/com/provedcode/talent/model/dto/ShortTalentDTO.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/service/impl/TalentServiceImpl.java
  src/main/java/com/provedcode/user/controller/AuthenticationController.java
  src/main/java/com/provedcode/user/mapper/UserInfoMapper.java
  src/main/java/com/provedcode/user/mapper/impl/UserInfoMapperImpl.java
  src/main/java/com/provedcode/user/model/Role.java
  src/main/java/com/provedcode/user/model/dto/RegistrationDTO.java
  src/main/java/com/provedcode/user/model/dto/SessionInfoDTO.java
  src/main/java/com/provedcode/user/model/entity/Authority.java
  src/main/java/com/provedcode/user/model/entity/UserAuthority.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/repo/AuthorityRepository.java
  src/main/java/com/provedcode/user/repo/UserAuthorityRepository.java
  src/main/java/com/provedcode/user/repo/UserInfoRepository.java
  src/main/java/com/provedcode/user/service/AuthenticationService.java
  src/main/java/com/provedcode/user/service/impl/AuthenticationServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: :frog: backend, user story #2
