Repository ProvedCode/backend, pull requests merged in 2023-05, with the labels that each got.

#118 S4.1T1-3
  src/main/java/com/provedcode/aws/service/S3Service.java
  src/main/java/com/provedcode/talent/controller/TalentSkillsController.java
  src/main/java/com/provedcode/talent/model/dto/ProofSkillsDTO.java
  src/main/java/com/provedcode/talent/model/entity/Skills.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/repo/SkillsRepository.java
  src/main/java/com/provedcode/talent/service/TalentSkillsService.java
Labels: :frog: backend, user story #1

#119 S4.1 tasks 4 5
  src/main/java/com/provedcode/talent/controller/TalentSkillsController.java
  src/main/java/com/provedcode/talent/model/dto/SkillsOnProofDTO.java
  src/main/java/com/provedcode/talent/service/TalentSkillsService.java
  src/main/resources/db/changelog/changeset/V4/data-V4.1.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: :frog: backend, user story #1

#121 S4.1S2T1
  src/main/java/com/provedcode/aws/scheduler/UpdateScheduler.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/talent/controller/SkillController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/mapper/SkillMapper.java
  src/main/java/com/provedcode/talent/model/dto/SkillDTO.java
  src/main/java/com/provedcode/talent/repo/SkillsRepository.java
  src/main/java/com/provedcode/talent/service/SkillsService.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/TalentSkillsService.java
Labels: :frog: backend, user story #2, general

#129 S4.2US1T1
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/talent/controller/TalentSkillsController.java
  src/main/java/com/provedcode/talent/model/entity/Skills.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/model/entity/TalentSkills.java
  src/main/java/com/provedcode/talent/service/ProofSkillsService.java
  src/main/resources/db/changelog/changeset/V4/data-V4.1.sql
  src/main/resources/db/changelog/changeset/V4/schema-V4.sql
Labels: :frog: backend, user story #1

#131 S4.2US1T2-3
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/mapper/SkillMapper.java
  src/main/java/com/provedcode/talent/model/dto/FullTalentDTO.java
  src/main/java/com/provedcode/talent/model/dto/ShortTalentDTO.java
  src/main/java/com/provedcode/talent/model/dto/SkillDTO.java
  src/main/java/com/provedcode/talent/model/dto/SkillIdDTO.java
  src/main/java/com/provedcode/talent/model/dto/SkillsOnProofDTO.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/service/ProofSkillsService.java
  src/main/java/com/provedcode/talent/service/TalentService.java
Labels: :frog: backend, user story #1

#135 S4.2-FULL
  src/main/java/com/provedcode/handlers/TalentExceptionHandler.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/repo/TalentRepository.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/util/annotations/doc/controller/proof/DeleteProofApiDoc.java
  src/main/resources/db/changelog/changeset/V4/data-V4.1.sql
  src/main/resources/db/changelog/changeset/V4/data-V4.2.sql
  src/main/resources/db/changelog/changeset/V4/data-V4.sql
  src/main/resources/db/changelog/changeset/V4/schema-V4.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: :frog: backend, user story #2

#127 S4.1
  src/main/java/com/provedcode/aws/scheduler/UpdateScheduler.java
  src/main/java/com/provedcode/aws/service/S3Service.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/talent/controller/SkillController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/controller/TalentSkillsController.java
  src/main/java/com/provedcode/talent/mapper/SkillMapper.java
  src/main/java/com/provedcode/talent/mapper/TalentMapper.java
  src/main/java/com/provedcode/talent/model/dto/ProofSkillsDTO.java
  src/main/java/com/provedcode/talent/model/dto/SkillDTO.java
  src/main/java/com/provedcode/talent/model/dto/SkillsOnProofDTO.java
  src/main/java/com/provedcode/talent/model/entity/Skills.java
  src/main/java/com/provedcode/talent/model/entity/Talent.java
  src/main/java/com/provedcode/talent/model/entity/TalentProof.java
  src/main/java/com/provedcode/talent/model/entity/TalentSkills.java
  src/main/java/com/provedcode/talent/model/entity/TalentTalents.java
  src/main/java/com/provedcode/talent/model/request/EditTalent.java
  src/main/java/com/provedcode/talent/repo/SkillsRepository.java
  src/main/java/com/provedcode/talent/repo/TalentRepository.java
  src/main/java/com/provedcode/talent/service/SkillsService.java
  src/main/java/com/provedcode/talent/service/TalentProofService.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/talent/service/TalentSkillsService.java
  src/main/resources/db/changelog/changeset/V4/data-V4.1.sql
  src/main/resources/db/changelog/changeset/V4/data-V4.sql
  src/main/resources/db/changelog/changeset/V4/drop-V4.sql
  src/main/resources/db/changelog/changeset/V4/schema-V4.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: :frog: backend

#146 S5 us3
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/controller/TalentProofController.java
  src/main/java/com/provedcode/talent/model/dto/StatisticsDTO.java
  src/main/java/com/provedcode/talent/service/TalentService.java
Labels: user story, :frog: backend, user story #3

#147 S5US1T3-4
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/kudos/controller/KudosController.java
  src/main/java/com/provedcode/kudos/repository/KudosRepository.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/resources/application-dev.properties
  src/main/resources/db/changelog/changeset/V5/talent-schema-V5.sql
Labels: user story #1

#149 S5-email
  pom.xml
  src/main/java/com/provedcode/aws/controller/AWSS3BucketController.java
  src/main/java/com/provedcode/aws/service/FileService.java
  src/main/java/com/provedcode/aws/service/S3Service.java
  src/main/java/com/provedcode/config/EmailConfig.java
  src/main/java/com/provedcode/config/EmailDefaultProps.java
  src/main/java/com/provedcode/config/SecurityConfig.java
  src/main/java/com/provedcode/config/ServerInfoConfig.java
  src/main/java/com/provedcode/handlers/GlobalControllerAdvice.java
  src/main/java/com/provedcode/kudos/controller/KudosController.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/sponsor/controller/SponsorController.java
  src/main/java/com/provedcode/sponsor/service/SponsorService.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/service/TalentService.java
  src/main/java/com/provedcode/user/controller/AuthenticationController.java
  src/main/java/com/provedcode/user/model/entity/DeletedUser.java
  src/main/java/com/provedcode/user/model/entity/UserInfo.java
  src/main/java/com/provedcode/user/repo/DeletedUserRepository.java
  src/main/java/com/provedcode/user/service/AuthenticationService.java
  src/main/java/com/provedcode/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/provedcode/user/service/impl/EmailService.java
  src/main/java/com/provedcode/user/util/UsersSchedulerService.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/changeset/V5/data-V5.sql
  src/main/resources/db/changelog/changeset/V5/deleted-user-schema.sql
  src/main/resources/db/changelog/changeset/V5/skills-data.sql
  src/main/resources/db/changelog/changeset/V5/user-info-schema-V5.sql
  src/main/resources/db/changelog/db.changelog-master.yaml
Labels: enhancement, :frog: backend, general

#152 Returning the old method
  src/main/java/com/provedcode/kudos/controller/KudosController.java
  src/main/java/com/provedcode/kudos/model/response/KudosAmountOnProofWithSponsor.java
  src/main/java/com/provedcode/kudos/service/KudosService.java
  src/main/java/com/provedcode/talent/controller/TalentController.java
  src/main/java/com/provedcode/talent/service/TalentService.java
Labels: bug
